version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 8.10
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket serverlesscicd --output-template-file outputSamTemplate.yaml
artifacts:
  name: build
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml